name: Release & Publish

on:
  push:
    tags:
      - v*

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: lvjiaxuan/github-action-templates/.github/workflows/lvr-release.yml@main
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: |
          pnpm i @antfu/ni -g
          pnpm i @vscode/vsce -g
          nci
          vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_PUBLISH }}
